spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 3000
        format_sql: true
        #use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false
      javax:
        persistence:
          query:
            timeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/order?autoReconnect=false&characterEncoding=UTF-8&useUnicode=true&characterEncoding=UTF-8&connectTimeout=5000&socketTimeout=6000&useSSL=false&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
#      connection-test-query: SELECT 1